### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jabcreations** [amrali-eg/EncodingChecker#4] opened 2021-02-24 11:37 UTC
I get "Object reference not set to an instance of an object." for both View and Validate options. I...

 - Chose a valid directory.
 - Selected a valid mask.
 - Chose Windows-1252 and UTF-8 character encodings.
 - I'm running Windows 10 and have .Net 4.8.03752 installed via Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full.

![fec](https://user-images.githubusercontent.com/5625045/108994789-3869c980-766a-11eb-9250-a6f3586ba8da.png)

**Comment by TemaSM** [comment] 2021-02-26 19:35
@jabcreations tried to reproduce issue, but no luck.
Please provide more details, maybe logs or .dmp files.
Or give info from Windows Event Log (here's instruction how to open and use it: http://www.devtopics.com/how-to-check-the-application-event-log-for-errors/) - interesting part is General and Details tabs contents of logged crash/error.

**Comment by jabcreations** [comment] 2021-02-27 02:38
Thank you for the special build. Both fortunately and unfortunately the errors no longer occur.

The errors originally occurred from whatever the build was that I downloaded the program yesterday via:
https://codeload.github.com/amrali-eg/EncodingChecker/zip/master

A side note: after converting when I change the directory the "Convert to:" changed from UTF-8 back to "us-ascii". By having the program change this you're going to get some people who don't back up their files first really really upset.

Now that this program is working I absolutely love it! As a fellow developer I too have had to deal with errors only occurring on client computers though never my own.

**Comment by TemaSM** [comment] 2021-02-28 15:39
Ok, great to hear that error disappeared somehow.
Probably it was environment problem. Anyway, this program should have better exceptions handling.
Issue may be closed on my opinion, until someone will face the same error again.
cc @amrali-eg

**Comment by jabcreations** [comment] 2021-02-28 17:25
Would you like me to test an updated build from the main Git link where I originally downloaded it from for some decisive certainty?

**Comment by TemaSM** [comment] 2021-02-28 17:43
I think it won't give us more info about source of error.
Better option here, is to [download ](https://ci.appveyor.com/api/buildjobs/5rrb0rj7p14w6e40/artifacts/EncodingChecker.zip) binary from my fork, where I implemented sending exceptions details to centralized server. So, whenever the exception occur, I will catch and will able to found source of error, and then fix it.

**Comment by jabcreations** [comment] 2021-02-28 20:01
Yeah, your fork works fine too. I'm confused though, you forked your own project, resumed someone else's project or...?

**Comment by TemaSM** [comment] 2021-02-28 20:55
I'm just OpenSource developer nd contributor to this repo, who someday used this program and sent PR with new features, then starred this repo
So, when you created new issue, I got notified and came here to help somehow =)

I will try my best in future when got spare time, with porting this program to maybe .Net Core, because this tool may be really helpful to someone, as it helped me in past for example.

**Comment by jabcreations** [comment] 2021-02-28 21:10
Ah okay, I appreciate it! I'm sure anyone else who encounters the issue (and bothers to search) will too.

.NET? What language is it written in currently? - Once my web business gets to a certain point I'm going to create an actually usable version of Linux that non-technical people will be able to use (e.g. explaining how to use the Terminal means a failure point for usability for non-technical people and producers) and I'll be staying clear of languages that aren't open source because I have no interest in politics. I plan on ensuring this type of functionality is available and easy to use.

**Comment by TemaSM** [comment] 2021-02-28 22:31
Currently this program coded using C# and .Net Framework 4 which is almost deprecated.
With .Net Core we can make this program works on any type of platform, including Linux, macOS, and Windows of course, even with GUI for each of them.
I agreed with you about opensource and good products for non-technical people.
So, if you wanna get any commercial based support by me for your business (any type, like donations and so on), including software development, feel free to contact me.  :)

**Comment by CadmiumTelluride** [comment] 2021-03-03 23:45
Dear coding friends, the error occurs when there is no Settings.bin file. The file is created when the app is closed. 
The simplest way to solve it is to add the following to the MainForm(), before the closing bracket:

if (_settings == null) SaveSettings();


cheers!

**Comment by jabcreations** [comment] 2021-03-03 23:50
The version that worked has the following files in the directory:

- EncodingChecker.exe
- EncodingUtils.dll
- Newtonsoft.Json.dll
- SharpRaven.dll
- Newtonsoft.Json.xml
- EncodingChecker.pdb
- EncodingUtils.pdb

Also Tema, I'm not sure which email address to contact you at, message me through my contact form at jabcreations.com if you're interested in the web, browser and OS projects.

**Comment by TemaSM** [comment] 2021-03-03 23:52
@CadmiumTelluride Thanks for info, will check it, because after trying to reproduce - everything works.
Think it's issue with creating `Settings.bin` file at startup time of program, when `%User%/AppData/Roaming/EncodingChecker/` somehow non-writable directory at runtime.

**Comment by jabcreations** [comment] 2021-03-03 23:57
I was not aware of that file, renamed it temporarily, ran the program and it was able to run fine. Keep in mind I'm using Tema's fork.

**Comment by CadmiumTelluride** [comment] 2021-03-04 00:56
I didn't get any non-writable issues, then again my path came out to the \AppData\Roaming\EncodingChecker. There might be something to consider with user permissions if the path comes out to \Local, but overall i would say its unlikely.

**Closed** 2021-03-22 22:07 UTC

**Comment by amrali-eg** [comment] 2021-03-23 04:07
> Dear coding friends, the error occurs when there is no Settings.bin file. The file is created when the app is closed.
> The simplest way to solve it is to add the following to the MainForm(), before the closing bracket:
> 
> if (_settings == null) SaveSettings();
> 
> cheers!

Dear CadmiumTelluride 

That was exactly the cause of the error. Fixed now.
Thanks.
